### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by 27Fer12** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-27Fer12#1]
[LENGUAJE TYPESCRIPT_fernanda.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-27Fer12/files/15204657/LENGUAJE.TYPESCRIPT_fernanda.pdf)

**Comment by josealfredo79** [comment]
Necesito avanzar con la calificaciòn...no se ha calificado...

**Comment by josealfredo79** [comment]
Calificación 18
